### PR TITLE
Add cheonjiin layout

### PR DESCRIPTION
**Pull request by topiasv**
Implements a Cheonjiin layout based on the Naratgeul layout utilizing [Hangul.js](https://github.com/e-/Hangul.js) for easy jamo assemble.

### CODE REVIEW

**Comment by peremen** [comment]
Thank you very much for fixes and additions! I am on a holiday, I will bump the release after coming back.

**Comment by topiasv** [comment]
No problem, been a long time user of your keyboard so just giving back. I would like to improve upon this even more. Enjoy your holidays!

**Comment by peremen** [comment]
Thanks for contribution. One future suggestion on Cheonjiin keyboard is auto-commit timer: unlike Naratgeul keyboard, Jaum clash on Cheonjiin keyboard is inevitable. For example, when entering "안녕" ㄴ needs to be entered twice. To make it possible, ㄴ -> right arrow -> ㄴ needs to be tapped. The "right arrow" step could be replaced by waiting for some time.

Also, to make user experience more streamlined, I will adjust Naratgeul keyboard's special key layout before actually releasing the package.

**Comment by topiasv** [comment]
Good suggestion, I was planning to add that feature later. I'm also making a cheonjiin plus layout with splitted jaum that will also avoid this problem. May I ask how you plan on adjusting the naratgeul symbol layout? I think tilde ~ should be on the first symbol page. Also maybe moving the side buttons for naratgeut to match the cheonjiin layout would be good.

**Comment by peremen** [comment]
Symbol layout of Naratgeul layout was not adjusted; only the position of paste, shift, symbol key was modified. I agree that 10-key layouts needs to share common symbol layout too, though no concrete plan exist.

**Comment by topiasv** [comment]
How about using the comma and period keys for some symbols instead of having them as constant period and comma? Same thing I did with cheonjiin. There many buttons available for symbol usage so utilizing all keys would be wise I think.

Also do you have kakaotalk or telegram or something? We could take this development discussion there. Send me your id to my email if you want to add me toxip@disroot.org.

**Pull request merged**
