### PR TITLE
Add vega layout and change versioning scheme to semantic versioning

### PR DESCRIPTION
**Pull request by topiasv**
Vega layout seems to be somewhat popular so this adds this layout with a trivial extension to the cheonjiin and naratgeul input processor. Also it's probably better to use semantic versioning for packet versions as that probably makes more sense.

### CODE REVIEW

**Comment by topiasv** [comment]
Accents isn't the best solutions for handling edge cases like ㄱ in words like 학교. It's very ugly as the popper is unable to handle keys that have labels with more than 1 character. However it works as a stop gap solution for now. Perhaps some sort of auto commit timer could help or a perhaps hold to input the same key feature would do the trick better.

**Comment by peremen** [comment]
Sorry for late response, I was busy during last month. Yes, I am okay with this version numbering bump too.

**Comment by peremen** [comment]
Okay, I found a bug in VEGA layout. I tried to enter following texts using these sequences:
 * "귀요미" - "ㄱㅋ", "ㅜㅠ", "ㅡㅣ"
 * "괴를리츠" - "ㄱㅋ", "ㅗㅛ", "ㅡㅣ"

Then characters "귀" and "괴" is not correctly composed, and "구ㅣ", "고ㅣ" is displayed instead. Other combining vowels seems fine to me.

**Comment by topiasv** [comment]
ah. it seems that it needs to be added to the "overflow" list similar to the dot ㆍ in cheonjiin input. That extends the pre-edit string from one syllable to two syllables temporarily to allow combining it with the previous vowel... Now that I think of it, I also didn't add some of the keys into the "combinable_jong" list which prevents the same from happening for certain combinations of ending consonants. The layout has mostly similar consonant keys as cheonjiin so didn't really notice that either. Didn't really go through extensive testing for this layout and as a result got many bugs >_>

**Comment by topiasv** [comment]
I realised I could make an easy fix for this but this would actually affect the cheonjiin for extending the pre-edit for 고ㅡ even though there is no need for it... The dot arae'a ㆍ was handled with a simple check but I guess I should make a similar list for handling cases with the vowel part.

**Comment by topiasv** [comment]
Okay, should be fixed now. Also added some comments and made the code a bit more clearer for some parts. Should probably change the name of the input handler since it now handles more than just cheonjiin and naratgeul. Could you test it a little bit more in case there are any other bugs there.

**Comment by peremen** [comment]
Yup, looks good. Thank you.

I am thinking about a test suite which could be integrated into build, just a future plan.

**Pull request merged**
